// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-app-overview.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/content.ts
var APP_STORE_URL = "https://apps.apple.com/us/app/endlessxr/id6751106381";
var SITE_URL = "https://endlessxr-xrhub-platform.lovable.app";
var overview = {
  name: "EndlessXR",
  tagline: "Create, Share, Explore XR \u2014 All in One Place.",
  description: "EndlessXR is an all-in-one short-form XR platform where you can effortlessly create and discover immersive experiences. It brings creation, editing, publishing, and discovery into one seamless headset-native ecosystem so immersive content can scale as fast as XR hardware.",
  availability: "Now available on Apple Vision Pro",
  appStoreUrl: APP_STORE_URL,
  siteUrl: SITE_URL,
  capabilities: ["Create", "Edit", "Publish", "Discover"]
};
var problems = [
  {
    title: "Content Lag",
    description: "Spatial interfaces are evolving fast - but immersive content isn't keeping up."
  },
  {
    title: "High Costs",
    description: "Creators struggle with fragmented tools and extreme production costs."
  },
  {
    title: "User Friction",
    description: "Users face major friction in accessing high-quality XR experiences."
  }
];
var features = [
  {
    title: "Various Content Types",
    description: "Support for Multi-2D, 360\xB0 Immersive, and Hybrid 2D+3D formats. Mix multiple media types into one experience."
  },
  {
    title: "Instant Discovery",
    description: "Short-form XR content feed removes friction. Discover instantly and give feedback to creators in real-time."
  },
  {
    title: "Headset-Native Editor",
    description: "Build directly in the headset with a unified spatial timeline. No complex desktop workflows required."
  },
  {
    title: "AI-Generation Tools",
    description: "Generate 3D models and 360\xB0 videos from text and images. Professional results with zero modeling expertise."
  }
];
var missionBenefits = [
  "Lower the barrier to XR content creation and consumption",
  "Help the industry move beyond early adopters",
  "Cross the chasm toward mainstream adoption"
];

// src/lib/mcp/tools/get-app-overview.ts
var get_app_overview_default = defineTool({
  name: "get_app_overview",
  title: "Get app overview",
  description: "Return the EndlessXR product overview: tagline, description, platform availability, core capabilities, mission, and links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const data = { ...overview, mission: missionBenefits };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/list-features.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_features_default = defineTool2({
  name: "list_features",
  title: "List product features",
  description: "List the EndlessXR product highlights, each with a title and description.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(features, null, 2) }],
    structuredContent: { features }
  })
});

// src/lib/mcp/tools/list-problems.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_problems_default = defineTool3({
  name: "list_xr_content_gap_problems",
  title: "List XR content gap problems",
  description: "List the industry problems EndlessXR addresses: the XR content gap, production costs, and user friction.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(problems, null, 2) }],
    structuredContent: { problems }
  })
});

// src/lib/mcp/tools/get-download-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_download_info_default = defineTool4({
  name: "get_download_info",
  title: "Get download info",
  description: "Return where and how to get EndlessXR: supported platform and the App Store and website links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const data = {
      platform: "Apple Vision Pro",
      availability: overview.availability,
      appStoreUrl: APP_STORE_URL,
      websiteUrl: SITE_URL
    };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "endlessxr-the-future-of-xr",
  title: "EndlessXR: The Future of XR",
  version: "0.1.0",
  instructions: "Public tools describing EndlessXR, a short-form XR platform for Apple Vision Pro. Use `get_app_overview` for the product summary and mission, `list_features` for product highlights, `list_xr_content_gap_problems` for the industry problems it addresses, and `get_download_info` for platform and download links. All data is public marketing content.",
  tools: [get_app_overview_default, list_features_default, list_problems_default, get_download_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
